import { IIngredient, IStep, DifficultyLevel } from "@/app/types";

interface RecipeSeed {
  title: string;
  image: string;
  prepTime: number;
  difficulty: DifficultyLevel;
  description: string;
  servings: number;
  ingredients: IIngredient[];
  steps: IStep[];
}

export const mockRecipes: RecipeSeed[] = [
  {
    title: "Spaghetti Carbonara",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
    prepTime: 30,
    difficulty: "medium",
    description: "A classic Italian pasta dish with a creamy egg and cheese sauce, crispy pancetta, and black pepper.",
    servings: 4,
    ingredients: [
      { name: "Spaghetti", amount: "400", unit: "g" },
      { name: "Pancetta or guanciale", amount: "200", unit: "g" },
      { name: "Eggs", amount: "4", unit: "large" },
      { name: "Pecorino Romano", amount: "100", unit: "g" },
      { name: "Parmesan", amount: "50", unit: "g" },
      { name: "Black pepper", amount: "2", unit: "tsp" },
      { name: "Salt", amount: "1", unit: "tbsp" },
    ],
    steps: [
      { stepNumber: 1, description: "Bring a large pot of salted water to a boil and cook spaghetti until al dente." },
      { stepNumber: 2, description: "Meanwhile, cook pancetta in a large skillet over medium heat until crispy. Remove from heat." },
      { stepNumber: 3, description: "Whisk together eggs, grated Pecorino Romano, Parmesan, and plenty of black pepper in a bowl." },
      { stepNumber: 4, description: "Reserve 1 cup of pasta cooking water before draining the spaghetti." },
      { stepNumber: 5, description: "Add hot spaghetti to the skillet with pancetta. Remove from heat." },
      { stepNumber: 6, description: "Pour egg mixture over pasta, tossing quickly. Add pasta water gradually to create a creamy sauce." },
      { stepNumber: 7, description: "Serve immediately with extra cheese and black pepper." },
    ],
  },
  {
    title: "Chicken Caesar Salad",
    image: "https://images.unsplash.com/photo-1580013759032-c96505e24c1f?w=800",
    prepTime: 20,
    difficulty: "easy",
    description: "Crispy romaine lettuce with grilled chicken, homemade Caesar dressing, croutons, and shaved Parmesan.",
    servings: 2,
    ingredients: [
      { name: "Romaine lettuce", amount: "1", unit: "head" },
      { name: "Chicken breast", amount: "300", unit: "g" },
      { name: "Parmesan", amount: "60", unit: "g" },
      { name: "Croutons", amount: "1", unit: "cup" },
      { name: "Caesar dressing", amount: "4", unit: "tbsp" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    steps: [
      { stepNumber: 1, description: "Season chicken breast with salt, pepper, and olive oil." },
      { stepNumber: 2, description: "Grill chicken over medium-high heat for 6–7 minutes per side until cooked through. Let rest 5 minutes, then slice." },
      { stepNumber: 3, description: "Chop romaine lettuce into bite-sized pieces and place in a large bowl." },
      { stepNumber: 4, description: "Add Caesar dressing and toss to coat evenly." },
      { stepNumber: 5, description: "Top with sliced chicken, croutons, and shaved Parmesan. Serve immediately." },
    ],
  },
  {
    title: "Beef Tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
    prepTime: 25,
    difficulty: "easy",
    description: "Juicy seasoned ground beef in warm corn tortillas topped with fresh salsa, avocado, and sour cream.",
    servings: 4,
    ingredients: [
      { name: "Ground beef", amount: "500", unit: "g" },
      { name: "Corn tortillas", amount: "8", unit: "units" },
      { name: "Taco seasoning", amount: "2", unit: "tbsp" },
      { name: "Avocado", amount: "2", unit: "units" },
      { name: "Tomato", amount: "2", unit: "units" },
      { name: "Sour cream", amount: "4", unit: "tbsp" },
      { name: "Cheddar cheese", amount: "100", unit: "g" },
      { name: "Lime", amount: "2", unit: "units" },
      { name: "Fresh cilantro", amount: "1", unit: "handful" },
    ],
    steps: [
      { stepNumber: 1, description: "Cook ground beef in a skillet over medium-high heat, breaking it up until browned." },
      { stepNumber: 2, description: "Drain excess fat and add taco seasoning with a splash of water. Simmer 3 minutes." },
      { stepNumber: 3, description: "Dice tomatoes, mash avocado with lime juice and salt, shred cheese." },
      { stepNumber: 4, description: "Warm tortillas in a dry skillet or directly over a flame for 30 seconds each side." },
      { stepNumber: 5, description: "Fill tortillas with beef, then top with tomato, avocado, sour cream, cheese, and cilantro." },
    ],
  },
  {
    title: "Mushroom Risotto",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800",
    prepTime: 45,
    difficulty: "hard",
    description: "Rich and creamy Italian risotto loaded with mixed mushrooms, white wine, Parmesan, and fresh thyme.",
    servings: 4,
    ingredients: [
      { name: "Arborio rice", amount: "320", unit: "g" },
      { name: "Mixed mushrooms", amount: "400", unit: "g" },
      { name: "Vegetable broth", amount: "1.2", unit: "L" },
      { name: "White wine", amount: "150", unit: "ml" },
      { name: "Onion", amount: "1", unit: "medium" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Parmesan", amount: "80", unit: "g" },
      { name: "Butter", amount: "40", unit: "g" },
      { name: "Olive oil", amount: "3", unit: "tbsp" },
      { name: "Fresh thyme", amount: "4", unit: "sprigs" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    steps: [
      { stepNumber: 1, description: "Heat broth in a separate saucepan and keep it warm over low heat." },
      { stepNumber: 2, description: "Sauté diced onion and garlic in olive oil over medium heat until translucent, about 5 minutes." },
      { stepNumber: 3, description: "Add mushrooms and thyme, cook until mushrooms are golden and liquid has evaporated, about 8 minutes." },
      { stepNumber: 4, description: "Add Arborio rice and toast for 2 minutes, stirring constantly." },
      { stepNumber: 5, description: "Pour in white wine and stir until absorbed." },
      { stepNumber: 6, description: "Add warm broth one ladle at a time, stirring continuously and waiting for each addition to absorb before adding the next." },
      { stepNumber: 7, description: "After about 18 minutes, when rice is creamy and al dente, remove from heat." },
      { stepNumber: 8, description: "Stir in butter and Parmesan. Season with salt and pepper. Rest 2 minutes before serving." },
    ],
  },
  {
    title: "Fluffy Buttermilk Pancakes",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800",
    prepTime: 15,
    difficulty: "easy",
    description: "Light and fluffy pancakes made with buttermilk for a tangy flavor. Perfect with maple syrup and fresh berries.",
    servings: 4,
    ingredients: [
      { name: "All-purpose flour", amount: "2", unit: "cups" },
      { name: "Buttermilk", amount: "480", unit: "ml" },
      { name: "Eggs", amount: "2", unit: "large" },
      { name: "Butter", amount: "4", unit: "tbsp" },
      { name: "Sugar", amount: "2", unit: "tbsp" },
      { name: "Baking powder", amount: "2", unit: "tsp" },
      { name: "Baking soda", amount: "1", unit: "tsp" },
      { name: "Salt", amount: "1/2", unit: "tsp" },
    ],
    steps: [
      { stepNumber: 1, description: "Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl." },
      { stepNumber: 2, description: "In another bowl, whisk buttermilk, eggs, and melted butter together." },
      { stepNumber: 3, description: "Pour wet ingredients into dry ingredients and stir until just combined — lumps are fine, do not overmix." },
      { stepNumber: 4, description: "Heat a non-stick pan over medium heat and lightly grease with butter." },
      { stepNumber: 5, description: "Pour 1/4 cup batter per pancake. Cook until bubbles form on the surface, about 2 minutes, then flip and cook 1 more minute." },
      { stepNumber: 6, description: "Serve immediately with maple syrup and fresh berries." },
    ],
  },
  {
    title: "Grilled Salmon with Lemon Butter",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800",
    prepTime: 25,
    difficulty: "medium",
    description: "Perfectly grilled salmon fillets with a zesty lemon butter sauce, served with steamed asparagus.",
    servings: 2,
    ingredients: [
      { name: "Salmon fillets", amount: "2", unit: "x 200g" },
      { name: "Butter", amount: "3", unit: "tbsp" },
      { name: "Lemon", amount: "2", unit: "units" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Fresh dill", amount: "2", unit: "tbsp" },
      { name: "Asparagus", amount: "200", unit: "g" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
      { name: "Salt and pepper", amount: "to taste" },
    ],
    steps: [
      { stepNumber: 1, description: "Pat salmon dry and season with salt, pepper, and olive oil on both sides." },
      { stepNumber: 2, description: "Preheat grill or grill pan over high heat." },
      { stepNumber: 3, description: "Grill salmon skin-side down for 4 minutes, then flip and cook 3 more minutes." },
      { stepNumber: 4, description: "Meanwhile, melt butter in a small pan over medium heat. Add minced garlic and lemon juice. Cook 2 minutes." },
      { stepNumber: 5, description: "Steam asparagus for 3–4 minutes until tender-crisp." },
      { stepNumber: 6, description: "Plate salmon and asparagus, drizzle with lemon butter sauce, and garnish with fresh dill." },
    ],
  },
  {
    title: "Vegetable Stir Fry",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800",
    prepTime: 20,
    difficulty: "easy",
    description: "A quick and colorful stir fry with crisp vegetables in a savory soy-ginger sauce, served over steamed rice.",
    servings: 3,
    ingredients: [
      { name: "Broccoli florets", amount: "200", unit: "g" },
      { name: "Bell peppers", amount: "2", unit: "units" },
      { name: "Snap peas", amount: "150", unit: "g" },
      { name: "Carrot", amount: "2", unit: "units" },
      { name: "Soy sauce", amount: "3", unit: "tbsp" },
      { name: "Fresh ginger", amount: "1", unit: "tbsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Sesame oil", amount: "1", unit: "tbsp" },
      { name: "Cornstarch", amount: "1", unit: "tsp" },
      { name: "Steamed rice", amount: "3", unit: "cups" },
    ],
    steps: [
      { stepNumber: 1, description: "Mix soy sauce, minced ginger, minced garlic, sesame oil, and cornstarch in a small bowl. Set aside." },
      { stepNumber: 2, description: "Heat a wok or large skillet over very high heat until smoking." },
      { stepNumber: 3, description: "Add oil and stir fry carrots and broccoli for 3 minutes." },
      { stepNumber: 4, description: "Add bell peppers and snap peas. Stir fry 2 more minutes." },
      { stepNumber: 5, description: "Pour sauce over vegetables and toss to coat. Cook 1 minute until sauce thickens." },
      { stepNumber: 6, description: "Serve immediately over steamed rice." },
    ],
  },
  {
    title: "Chocolate Lava Cake",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800",
    prepTime: 35,
    difficulty: "hard",
    description: "Decadent individual chocolate cakes with a warm, gooey molten center. Serve with vanilla ice cream.",
    servings: 4,
    ingredients: [
      { name: "Dark chocolate (70%)", amount: "200", unit: "g" },
      { name: "Butter", amount: "100", unit: "g" },
      { name: "Eggs", amount: "4", unit: "large" },
      { name: "Egg yolks", amount: "2", unit: "units" },
      { name: "Sugar", amount: "80", unit: "g" },
      { name: "All-purpose flour", amount: "40", unit: "g" },
      { name: "Cocoa powder", amount: "2", unit: "tbsp" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
      { name: "Pinch of salt", amount: "1", unit: "pinch" },
    ],
    steps: [
      { stepNumber: 1, description: "Preheat oven to 220°C (425°F). Grease 4 ramekins with butter and dust with cocoa powder." },
      { stepNumber: 2, description: "Melt chocolate and butter together in a heatproof bowl over simmering water. Let cool slightly." },
      { stepNumber: 3, description: "Whisk eggs, egg yolks, and sugar together until pale and thick, about 3 minutes." },
      { stepNumber: 4, description: "Fold chocolate mixture into the egg mixture until combined." },
      { stepNumber: 5, description: "Sift in flour and salt. Fold gently until just incorporated." },
      { stepNumber: 6, description: "Divide batter evenly among ramekins. Refrigerate for at least 10 minutes." },
      { stepNumber: 7, description: "Bake for exactly 12 minutes — edges should be set but center still jiggly." },
      { stepNumber: 8, description: "Let rest 1 minute, then run a knife around the edge and invert onto plates. Serve immediately with vanilla ice cream." },
    ],
  },
];
